### ISSUE TITLE
Error installing 'spark' package using dcos

### ISSUE THREAD

**Issue by natemurthy** [mesosphere/dcos-spark#28]
I have the DCOS command line interface installed on my local Linux machine. I successfully installed other services (e.g. HDFS, Kubernetes, Cassandra, etc.), but Spark has been problematic. Here's the error I get when I try installing the Spark package for DCOS:

```
$ dcos --log-level=ERROR package install spark 

Note that the Apache Spark DCOS Service is beta and there may be bugs, incomplete features, incorrect documentation or other discrepancies.
We recommend a minimum of two nodes with at least 2 CPU and 2GB of RAM available for the Spark Service and running a Spark job.
Note: The Spark CLI may take up to 5min to download depending on your connection.
Continue installing? [yes/no] yes

Installing Marathon app for package [spark] version [1.6.0]
Installing CLI subcommand for package [spark] version [1.6.0]

2016-03-18 11:48:43,776 /home/nate/Workspace/dcos/local/lib/python2.7/site-packages/dcos/subcommand.py:_execute_install:370 - Install script's stdout: Collecting dcos-spark==0.5.6 from https://downloads.mesosphere.com/spark/assets/dcos_spark-0.5.6-py2.py3-none-any.whl (from -r /tmp/tmpReeCPV (line 1))

2016-03-18 11:48:43,776 /home/nate/Workspace/dcos/local/lib/python2.7/site-packages/dcos/subcommand.py:_execute_install:371 - Install script's stderr: /home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Exception:
Traceback (most recent call last):
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 857, in _download_http_url
    stream=True,
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/nate/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Error installing 'spark' package.
Run with `dcos --log-level=ERROR` to see the full output.
```

Think it may be a Python 3.4 issue. Any way I can configure my `dcos` CLI to point to `pip3` instead of `pip` ? Or maybe I'm mistaken.

**Comment by natemurthy** [comment]
Interestingly, I don't observe this SSLError when running this command on my MacBook. But I do see the Mesos tasks fail when trying to upstart spark.

<img width="692" alt="spark-fail-dcos" src="https://cloud.githubusercontent.com/assets/1788878/13897651/710a9da6-ed75-11e5-9aef-10d6af3fa683.png">

**Comment by natemurthy** [comment]
You can view a sample `stderr` log from the Mesos sandbox of the failed Spark task [here](http://pastebin.com/Ef0PfAPZ).

**Comment by mgummelt** [comment]
I'll ask our CLI team about that install issue.

The "framework removed" error in the stderr log is what you see when you try to reinstall Spark without cleaning up first: https://docs.mesosphere.com/spark-1-7/ See "uninstall"

Try following those uninstall instructions, then installing fresh.

**Comment by tamarrow** [comment]
Looks like an SSL error. What's the value of `dcos config show core.ssl_verify`? If your core.dcos_url is https, we will try to verify ssl unless you set `core.ssl_verify` to false.

**Comment by natemurthy** [comment]
@mgummelt Deleted the znode corresponding to the earlier Spark instance. Going to try to re-install afresh now.

@tamarrow 
```
$ dcos config show core.ssl_verify
false
```

**Comment by natemurthy** [comment]
@mgummelt Alright, got Spark installed now after purging the stale ZooKeeper data. But having issues running jobs:
```
$ dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark -examples_2.11-1.6.0-SNAPSHOT.jar 30"
Spark distribution spark-1.6.0 not found locally.
It looks like this is your first time running Spark!
Downloading http://downloads.mesosphere.io.s3.amazonaws.com/spark/assets/spark-1.6.0.tgz...
Traceback (most recent call last):
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 301, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/requests/models.py", line 660, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 344, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
    sys.exit(main())
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/cli.py", line 98, in main
    return run_spark_job(args)
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/cli.py", line 43, in run_spark_job
    args['--verbose'])
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/spark_submit.py", line 164, in submit_job
    response = run(master, args, verbose, props)
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/spark_submit.py", line 278, in run
    command = _get_command(master, args)
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/spark_submit.py", line 346, in _get_command
    submit_file = spark_file(os.path.join('bin', spark_executable))
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/spark_submit.py", line 126, in spark_file
    return os.path.join(spark_dist(), path)
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/spark_submit.py", line 104, in spark_dist
    for block in resp:
  File "/home/nate/.dcos/subcommands/spark/env/lib/python3.4/site-packages/requests/models.py", line 663, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by mgummelt** [comment]
Looks like a connection failure during the Spark dist download.  That file is ~300MB.  Does this error happen everytime?  Does it spend some time downloading, then fail, or fail immediately?  Can you download that file using another tool (wget or curl)?

**Comment by natemurthy** [comment]
Does the `dcos spark run` command download the Spark binary to my local machine (the machine from which I execute the command, not the same as the machine(s) running Spark in my DCOS cluster)?

I'm seeing some really slow download times:
```
$ wget http://downloads.mesosphere.io.s3.amazonaws.com/spark/assets/spark-1.6.0.tgz
--2016-04-28 22:06:38--  http://downloads.mesosphere.io.s3.amazonaws.com/spark/assets/spark-1.6.0.tgz
Resolving downloads.mesosphere.io.s3.amazonaws.com (downloads.mesosphere.io.s3.amazonaws.com)... 54.231.114.3
Connecting to downloads.mesosphere.io.s3.amazonaws.com (downloads.mesosphere.io.s3.amazonaws.com)|54.231.114.3|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 233135068 (222M) [application/x-tar]
Saving to: ‘spark-1.6.0.tgz’

 3% [==>                                                                                                          ] 8,383,415   63.3KB/s  eta 30m 15s
```

So that might be half of the issue. M

So that might be half of the issue. M

**Comment by natemurthy** [comment]
Alright, I'm thinking closing this and filing a separate ticket. I've got the DCOS Spark CLI to successfully install, but now I'm hitting issues when running jobs:
![screenshot from 2016-04-28 22 42 00](https://cloud.githubusercontent.com/assets/1788878/14908955/b128e0b8-0d92-11e6-924d-b5941b580589.png)

**Comment by mgummelt** [comment]
It does download locally.  It's in a data directory in the virtualenv for spark in ~/.dcos/subcommands/spark/...

We should probably be more verbose about this, and let you configure that directory.  You definitely shouldn't get a 500.  You could look into the sandbox for the dispatcher at <dcos-url>/mesos and see if any of those logs help you.  You'll have to go down a couple subdirectories to find the actual dispatcher logs.

**Comment by natemurthy** [comment]
Here's what I found in my Mesos sandbox for the Spark job I tried to run:
```
I0429 05:46:12.858536 10749 logging.cpp:188] INFO level logging started!
I0429 05:46:12.858827 10749 fetcher.cpp:424] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/3d2be1b2-67bd-48bc-ac99-5c76d8970d7d-S1","items":[{"action":"BYPASS_CACHE","uri":{"extract":true,"value":"https:\/\/downloads.mesosphere.com.s3.amazonaws.com\/assets\/spark\/spark"}}],"sandbox_directory":"\/var\/lib\/mesos\/slave\/slaves\/3d2be1b2-67bd-48bc-ac99-5c76d8970d7d-S1\/frameworks\/3d2be1b2-67bd-48bc-ac99-5c76d8970d7d-0008\/executors\/driver-20160429054609-0002\/runs\/acd4f833-1ca5-4a6a-851e-6b3bbe224ab4"}
I0429 05:46:12.860232 10749 fetcher.cpp:379] Fetching URI 'https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark'
I0429 05:46:12.860254 10749 fetcher.cpp:250] Fetching directly into the sandbox directory
I0429 05:46:12.860275 10749 fetcher.cpp:187] Fetching URI 'https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark'
I0429 05:46:12.860292 10749 fetcher.cpp:134] Downloading resource from 'https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark' to '/var/lib/mesos/slave/slaves/3d2be1b2-67bd-48bc-ac99-5c76d8970d7d-S1/frameworks/3d2be1b2-67bd-48bc-ac99-5c76d8970d7d-0008/executors/driver-20160429054609-0002/runs/acd4f833-1ca5-4a6a-851e-6b3bbe224ab4/spark'
Failed to fetch 'https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark': Error downloading resource: SSL peer certificate or SSH remote key was not OK
```

**Comment by mgummelt** [comment]
```bash
$ dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark -examples_2.11-1.6.0-SNAPSHOT.jar 30"
```

You have a space between "spark" and "-examples".  Remove that and it should work.

**Comment by natemurthy** [comment]
Sorry, that was a typo when I copy-n-pasted. I'm seeing this error when that space is already removed.

**Comment by mgummelt** [comment]
That's strange then, because that's exactly the error you would see if you did have the space:

The mesos fetcher is trying to download `https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark`.  It thinks that is the jar.

**Comment by marctrem** [comment]
`downloads.mesosphere.com.s3.amazonaws.com`'s certificate is invalid :( . Until it's fixed, you can probably download the file elsewhere and get it from there.

**Comment by marctrem** [comment]
Nevermind, I get 403 while downloading the package. The automated installer gets its package from `https://downloads.mesosphere.com/spark/assets/spark-1.6.1-2.tgz` .
