### ISSUE TITLE
Unable to submit spark jobs

### ISSUE THREAD

**Issue by ahmed-menshawy** [mesosphere/dcos-spark#34]
**After installing spark from DC/OS CLI, I am not able to submit the simpe Pi example.**

**I used this command to submit the Pi task:**

`dcos spark run --submit-args="--class org.apache.spark.examples.SparkPi https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark-examples_2.10-1.4.0-SNAPSHOT.jar 30"`

**But it gives me the following error:**

```
Spark distribution spark-1.6.1-2 not found locally.
It looks like this is your first time running Spark!
Downloading https://downloads.mesosphere.com/spark/assets/spark-1.6.1-2.tgz...
ERROR:dcos.http:HTTP SSL Error
Traceback (most recent call last):
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/http.py", line 96, in _request
    **kwargs)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Traceback (most recent call last):
  File "/home/user/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
    sys.exit(main())
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/cli.py", line 102, in main
    return run_spark_job(args)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/cli.py", line 44, in run_spark_job
    args['--verbose'])
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 167, in submit_job
    response = run(dispatcher, args, verbose, props)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 281, in run
    command = _get_command(dispatcher, args)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 349, in _get_command
    submit_file = spark_file(os.path.join('bin', spark_executable))
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 129, in spark_file
    return os.path.join(spark_dist(), path)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 102, in spark_dist
    resp = http.request('GET', spark_uri, stream=True)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/http.py", line 222, in request
    verify=verify, **kwargs)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/util.py", line 524, in timer
    return fn(*args, **kwargs)
  File "/home/user/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos/http.py", line 104, in _request
    raise DCOSException(msg)
dcos.errors.DCOSException: An SSL error occurred. To configure your SSL settings, please run: `dcos config set core.ssl_verify <value>`
<value>: Whether to verify SSL certs for HTTPS or path to certs
```

**P.S. the value of "core.ssl_verify" is false**

**Comment by mgummelt** [comment]
@tamarrow Can you look at this?  Seems that `dcos.http` is having trouble with ssl

@ahmed-menshawy What is the output of:

`dcos spark --version`
`dcos --version`

**Comment by ahmed-menshawy** [comment]
Thanks @mgummelt  for replying

- The output for` dcos spark --version` is `dcos-spark version 0.5.17`
- The output for  `dcos --version `
```
dcoscli.version=0.4.6
dcos.version=1.7-open
dcos.commit=14509fe1e7899f439527fb39867194c7a425c771
dcos.bootstrap-id=3a2b7e03c45cd615da8dfb1b103943894652cd71
```

**Comment by tamarrow** [comment]
@ahmed-menshawy what is the output of `dcos config show`?

**Comment by ahmed-menshawy** [comment]
Thanks @tamarrow for replying:
The output of `dcos config show` is:
```
core.dcos_url=https://url
core.reporting=True
core.ssl_verify=false
core.timeout=5
```

**Comment by ahmed-menshawy** [comment]
@mgummelt @tamarrow do you have any suggestions for this problem? Really I am not able to move forward having this problem. Even I did multiple reinstallations for this and the same problem still exists.

**Comment by mgummelt** [comment]
@tamarrow should be looking into it.  She'll get back to you shortly.

**Comment by mgummelt** [comment]
You can also get real time support here: https://docs.mesosphere.com/support/

**Comment by erikriverson** [comment]
@ahmed-menshawy , I think I'm working around until it's fixed this by setting core.sslverify to false, changing the core.dcos_url to use HTTP procotol, not HTTPS, and then re-logging into dcos with dcos auth login.

**Comment by ahmed-menshawy** [comment]
@erikriverson I did this, but still I am getting the same error.
The output of `dcos config show` is:
'core.dcos_acs_token=********
core.dcos_url=http://daatic-dc-elasticl-.eu-west-1.elb.amazonaws.com
core.reporting=True
core.ssl_verify=false
core.timeout=5'

Then I logged out using `dcos auth logout` and logged in again.

**Comment by mgummelt** [comment]
I made a CLI issue to track this: https://github.com/dcos/dcos-cli/issues/686

**Comment by ANierbeck** [comment]
One workaround seems to download the tgz in question and using plain spark. 
But when trying to deploy the PI sample we got an issue running the PI application on the cluster because the certificate isn't valid. 

It seems to be that this URL doesn't have a valid certificate: 
https://downloads.mesosphere.com.s3.amazonaws.com

**Comment by ANierbeck** [comment]
Workaround seems to be download the given Spark tgz and extract it to: 
.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/dcos_spark/data/spark-1.6.1-2
if the cli finds a spark there it doesn't need to download it.

**Comment by mgummelt** [comment]
I can't repro.

Can someone run with `dcos --log-level=debug` and post the results?

**Comment by mgummelt** [comment]
@ANierbeck where are you seeing a request to https://downloads.mesosphere.com.s3.amazonaws.com?  The request described is to https://downloads.mesosphere.com/spark/assets/spark-1.6.1-2.tgz.  It is backed by S3, but there's no redirect, so it shouldn't affect the SSL error.

**Comment by ANierbeck** [comment]
we where hacking on the dcos python scripts to show us the urls ...

**Comment by mgummelt** [comment]
Are you conflating the job URL with the dist URL?  The job URL in the OP is as you described, but the error in the OP is from the dist URL, which is on `downloads.mesosphere.com`

**Comment by ANierbeck** [comment]
ahh you're right copied the url from the wrong spot ... of course I meant to use this one: 
https://downloads.mesosphere.com ... sorry about that got confused with all those things we did try today. 

never the less the server gave us an error regarding the certificate, when we tried this morning (somewhere around 8-9 UTC)

**Comment by mgummelt** [comment]
Can you post the run and the output?

**Comment by ahmed-menshawy** [comment]
Now I am not able to install spark as a subcommand in DC/OS CLI -_- . When ever I ran this commend `dcos --log-level=ERROR package install spark` it's giving me the error below and spark gets installed only on the dashboard. [ any help please] 
```
Installing Marathon app for package [spark] version [1.0.1-1.6.1-2]
Installing CLI subcommand for package [spark] version [1.0.1-1.6.1-2]
MainThread: 2016-07-14 10:57:07,721 /home/abdelkader/dcos/local/lib/python2.7/site-packages/dcos/subcommand.py:_execute_command:581 - Command script's stdout: Collecting dcos-spark==0.5.18 from https://downloads.mesosphere.com/spark/assets/dcos_spark-0.5.18-py2.py3-none-any.whl (from -r /tmp/tmpeO5OJO (line 1))

MainThread: 2016-07-14 10:57:07,721 /home/abdelkader/dcos/local/lib/python2.7/site-packages/dcos/subcommand.py:_execute_command:582 - Command script's stderr: /home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Exception:
Traceback (most recent call last):
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
    wb.build(autobuilding=True)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 587, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 810, in unpack_url
    hashes=hashes
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 649, in unpack_http_url
    hashes)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 842, in _download_http_url
    stream=True,
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/abdelkader/.dcos/subcommands/spark/env/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Error installing 'spark' package.
Run with `dcos --log-level=ERROR` to see the full output.
```

**Comment by ahmed-menshawy** [comment]
Now he's giving me this error `Failed to fetch 'https://downloads.mesosphere.com.s3.amazonaws.com/assets/spark/spark-examples_2.10-1.5.0.jar': Error downloading resource: SSL peer certificate or SSH remote key was not OK` on the Pi task log viewer.

**Comment by issenec** [comment]
@ahmed-menshawy I've seen that SSLError before - Could it be because your Python is too old (which is the case if you're using default Python in CentOS 7)?

**Comment by ahmed-menshawy** [comment]
@issenec you're right. Yesterday I upgraded python to 2.7.11 and it worked fine.

**Comment by mgummelt** [comment]
We're migrating to binary CLIs with python embedded, which should solve many of these compatibility problems.
