### ISSUE TITLE
Cannot install dcos spark cli with DC/OS 1.8

### ISSUE THREAD

**Issue by martinstuder** [mesosphere/dcos-spark#35]
Trying to install the DC/OS Spark CLI with DC/OS 1.8 fails. The same has worked with DC/OS 1.7.

```
mstuder@falcon:~/dcos$ dcos --log-level=DEBUG package install spark --cli
MainThread: 2016-08-08 21:01:31,441 dcos/http.py:_request:87 - Sending HTTP ['get'] to ['http://dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com/capabilities']: {'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1'}
MainThread: 2016-08-08 21:01:31,448 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:213 - Starting new HTTP connection (1): dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com
MainThread: 2016-08-08 21:01:31,599 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:395 - "GET /capabilities HTTP/1.1" 200 82
MainThread: 2016-08-08 21:01:31,601 dcos/http.py:_request:117 - Received HTTP response [200]: {'Content-Type': 'application/vnd.dcos.capabilities+json;charset=utf-8;version=v1', 'Server': 'openresty/1.9.15.1', 'Connection': 'keep-alive', 'Content-Length': '82', 'Date': 'Mon, 08 Aug 2016 19:01:31 GMT'}
MainThread: 2016-08-08 21:01:31,601 dcos/util.py:timer:529 - duration: dcos.http._request: 0.16s
MainThread: 2016-08-08 21:01:31,602 dcos/http.py:_request:87 - Sending HTTP ['post'] to ['http://dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com/package/describe']: {'Content-Type': 'application/vnd.dcos.package.describe-request+json;charset=utf-8;version=v1', 'Accept': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2'}
MainThread: 2016-08-08 21:01:31,604 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_new_conn:213 - Starting new HTTP connection (1): dcos-elasticloadba-gs37t0u7mxpm-42049901.eu-central-1.elb.amazonaws.com
MainThread: 2016-08-08 21:01:31,755 cli/env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:_make_request:395 - "POST /package/describe HTTP/1.1" 200 13068
MainThread: 2016-08-08 21:01:31,815 dcos/http.py:_request:117 - Received HTTP response [200]: {'Content-Type': 'application/vnd.dcos.package.describe-response+json;charset=utf-8;version=v2', 'Server': 'openresty/1.9.15.1', 'Connection': 'keep-alive', 'Content-Length': '13068', 'Date': 'Mon, 08 Aug 2016 19:01:31 GMT'}
MainThread: 2016-08-08 21:01:31,815 dcos/util.py:timer:529 - duration: dcos.http._request: 0.21s
Installing CLI subcommand for package [spark] version [1.0.1-2.0.0]
MainThread: 2016-08-08 21:01:31,816 dcos/util.py:ensure_dir_exists:129 - Creating directory: '/home/mstuder/.dcos/subcommands/spark'
MainThread: 2016-08-08 21:01:31,817 dcos/subcommand.py:_execute_command:571 - Calling: ['/usr/local/bin/virtualenv', '--version']
MainThread: 2016-08-08 21:01:31,859 dcos/subcommand.py:_execute_command:584 - Command script's stdout: b'15.0.2\n'
MainThread: 2016-08-08 21:01:31,860 dcos/subcommand.py:_execute_command:585 - Command script's stderr: b''
MainThread: 2016-08-08 21:01:31,860 dcos/subcommand.py:_execute_command:571 - Calling: ['/usr/local/bin/virtualenv', '/home/mstuder/.dcos/subcommands/spark/env']
MainThread: 2016-08-08 21:01:32,658 dcos/subcommand.py:_execute_command:581 - Command script's stdout: b'New python executable in /home/mstuder/.dcos/subcommands/spark/env/bin/python\nInstalling setuptools, pip, wheel...\n  Complete output from command /home/mstuder/.dcos/...spark/env/bin/python - setuptools pip wheel:\n  Traceback (most recent call last):\n  File "<stdin>", line 7, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/index.py", line 30, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/wheel.py", line 39, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/scripts.py", line 14, in <module>\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.1.2-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 31, in <module>\nImportError: cannot import name HTTPSHandler\n----------------------------------------\n...Installing setuptools, pip, wheel...done.\n'
MainThread: 2016-08-08 21:01:32,658 dcos/subcommand.py:_execute_command:582 - Command script's stderr: b'Traceback (most recent call last):\n  File "/usr/local/bin/virtualenv", line 11, in <module>\n    sys.exit(main())\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 711, in main\n    symlink=options.symlink)\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 944, in create_environment\n    download=download,\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 900, in install_wheel\n    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)\n  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 795, in call_subprocess\n    % (cmd_desc, proc.returncode))\nOSError: Command /home/mstuder/.dcos/...spark/env/bin/python - setuptools pip wheel failed with error code 1\n'
Error installing 'spark' package.
Run with `dcos --log-level=ERROR` to see the full output.
```

I'm running on Ubuntu 16.04.01 LTS.

**Comment by mgummelt** [comment]
This seems to be an error with `dcos-cli`.  Please open here https://github.com/dcos/dcos-cli
