### ISSUE TITLE
'dcos spark status ...' error, empty respond from server

### ISSUE THREAD

**Issue by ohal** [mesosphere/dcos-spark#5]
everything below is running under Mesos DCOS cluster.
```
$ dcos --version
dcos version 0.1.8
$ dcos spark --version
dcos-spark version 0.1.0
```
while launching and checking jar job got the next output:
```
$ dcos spark run --submit-args='--class org.apache.spark.examples.SparkPi http://some-accessible-web-server/spark.jar 50'
Run job succeeded. Submission id: driver-20150617160027-0012
```
log4j logs:
```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/06/17 16:00:26 INFO RestSubmissionClient: Submitting a request to launch an application in mesos://ansdcos-control-01//service/sparkcli/.
15/06/17 16:00:26 INFO RestSubmissionClient: Submission successfully created as driver-20150617160027-0012. Polling submission state...
15/06/17 16:00:26 INFO RestSubmissionClient: Submitting a request for the status of submission driver-20150617160027-0012 in mesos://ansdcos-control-01//service/sparkcli/.
15/06/17 16:00:27 INFO RestSubmissionClient: State of driver driver-20150617160027-0012 is now RUNNING.
15/06/17 16:00:27 INFO RestSubmissionClient: Server responded with CreateSubmissionResponse:
{
  "action" : "CreateSubmissionResponse",
  "serverSparkVersion" : "1.4.0",
  "submissionId" : "driver-20150617160027-0012",
  "success" : true
}
15/06/17 16:00:27 INFO Utils: Shutdown hook called
```
then checking status:
```
$ dcos spark status driver-20150617121129-0012
```
log4j logs:
```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
15/06/17 16:00:40 INFO RestSubmissionClient: Submitting a request for the status of submission driver-20150617121129-0012 in mesos://ansdcos-control-01//service/sparkcli/.
15/06/17 16:00:41 ERROR RestSubmissionClient: Error: Server responded with message of unexpected type SubmissionStatusResponse.
15/06/17 16:00:41 INFO Utils: Shutdown hook called
```
and ```dcos spark status driver-20150617121129-0012``` failing with trace back because NULL respond:
```
Traceback (most recent call last):
  File "/home/ohalenok/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
    sys.exit(main())
  File "/home/ohalenok/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 64, in main
    return job_status(args)
  File "/home/ohalenok/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 36, in job_status
    return spark_submit.job_status(master(), args['<submissionId>'])
  File "/home/ohalenok/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 53, in job_status
    response = run(master, ["--status", submissionId])
  File "/home/ohalenok/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark
/spark_submit.py", line 150, in run
    response = json.loads(err[err.index('{'):err.index('}') + 1])
ValueError: substring not found
```
job itself is running well without any issues and gives Pi value

**Comment by Y4Rv1K** [comment]
Any updates related to this issue?

**Comment by ssk2** [comment]
Apologies @Y4Rv1K - I'll chase this up!

**Comment by Y4Rv1K** [comment]
Hello, somebody know how to fix it?

**Comment by tnachen** [comment]
Hi Y4Rv1K, sorry didn't see your issue until now.

I think I've fixed this issue a while back and already pushed out a new client. Sorry I didn't bump the client version since it's still very early and didn't try to track versions yet.

Can you try reinstalling the spark cli and try again?

Dcos package uninstall --cli spark
dcos package install --cli spark

**Comment by AndriiOmelianenko** [comment]
@tnachen I've reinstalled spark cli with commands above, ran spark job, wanted to check it's status and got this:
```
$ dcos spark status driver-20150717081852-0002
Traceback (most recent call last):
  File "/home/centos/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
    sys.exit(main())
  File "/home/centos/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 67, in main
    return job_status(args)
  File "/home/centos/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/cli.py", line 39, in job_status
    return spark_submit.job_status(master(), args['<submissionId>'])
  File "/home/centos/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 53, in job_status
    response = run(master, ["--status", submissionId])
  File "/home/centos/.dcos/subcommands/spark/env/lib/python2.7/site-packages/dcos_spark/spark_submit.py", line 148, in run
    response = json.loads(err[err.index('{'):err.index('}') + 1])
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 4 column 15 (char 86)
```

**Comment by AndriiOmelianenko** [comment]
when job is still running output is normal.
```
$ dcos spark status driver-20150717114058-0001
Submission ID: driver-20150717114058-0001
Driver state: RUNNING
```
But when it's finished output is like one post above.

**Comment by AndriiOmelianenko** [comment]
Guys, do we have any updates on this?

**Comment by tnachen** [comment]
This should be fixed with latest master. Please reopen if this isn't.
