### ISSUE TITLE
dcos spark run --help fail

### ISSUE THREAD

**Issue by besil** [mesosphere/dcos-spark#9]
Hi, I'm having issues running the above command

```
$ dcos spark run --help
Traceback (most recent call last):
  File "/Users/besil/.dcos/subcommands/spark/env/bin/dcos-spark", line 11, in <module>
    sys.exit(main())
  File "/Users/besil/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/cli.py", line 63, in main
    return show_spark_submit_help()
  File "/Users/besil/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/cli.py", line 35, in show_spark_submit_help
    return spark_submit.show_help()
  File "/Users/besil/.dcos/subcommands/spark/env/lib/python3.4/site-packages/dcos_spark/spark_submit.py", line 34, in show_help
    for line in stderr.split("\n"):
TypeError: 'str' does not support the buffer interface
```

I think I found the error, I'm patching it right now

**Comment by tnachen** [comment]
This is fixed now.
